# Step 1: Fetch the CSRF token (if provided by a specific endpoint)
GET http://localhost:3001/auth/csrf-token
Content-Type: application/json

### Step 2: Use the CSRF token in the login request
POST http://localhost:3001/auth/login
Content-Type: application/json
X-CSRF-Token: pSTGgOO9-Axs8oJ9eZVvZyEcVpv5p9xya9mU

{
  "username": "baz",
  "password": "barbarbar"
}

### Get user by ID
GET http://localhost:3001/user/me

### Logout
POST http://localhost:3001/auth/logout
X-CSRF-Token: Y4LSPaDy-A1obEegvcwnV7VuH5NjLeAz-PsI


### Get all users
GET http://localhost:3001/user