# Step 1: Fetch the CSRF token (if provided by a specific endpoint)
GET http://localhost:3001/auth/csrf-token
Content-Type: application/json

### Step 2: Use the CSRF token in the login request
POST http://localhost:3001/auth/login
Content-Type: application/json
X-CSRF-Token: rIgukw3E-ziLNnOBje2Uwpml4gGNSLP_tN74

{
  "username": "baz",
  "password": "barbarbar"
}

### Get user by ID
GET http://localhost:3001/user/profile

### Logout
POST http://localhost:3001/auth/logout
X-CSRF-Token: IrIgukw3E-ziLNnOBje2Uwpml4gGNSLP_tN74


### Get all users
GET http://localhost:3001/user