### Create a new note
POST http://localhost:3001/note/
Content-Type: application/json
{
    "userId": "ac8ec097-2047-4009-9c91-04a63047b04e",
    "title": "My First Note"
}

### Get note
GET http://localhost:3001/note/7c0a05f9-1e54-42cf-a540-11b20f576237

### Get all notes for a user
GET http://localhost:3001/note/user/ac8ec097-2047-4009-9c91-04a63047b04e