### Create a new note
POST http://localhost:3001/note/
Content-Type: application/json
X-CSRF-Token: wMW1NkWS-cY_OR7uJDVxdBdVka8NJMTpxOXc

{
    "title": "My First Note"
}

### Get note
GET http://localhost:3001/note/3b681cc8-f220-4e97-8f6f-69d37051cf97

### Get all notes for a user
GET http://localhost:3001/note

### Update note
PATCH http://localhost:3001/note/3b681cc8-f220-4e97-8f6f-69d37051cf97
Content-Type: application/json
X-CSRF-Token: wMW1NkWS-cY_OR7uJDVxdBdVka8NJMTpxOXc

{
    "title": "Updated Note Title",
    "content": "This is the updated content of the note.",
    "tags": ["reminder", "learning"],
    "isShared": true
}