### Create a new user
POST http://localhost:3001/user/
Content-Type: application/json

{
    "name": "foo",
    "username": "baz",
    "password": "barbarbar",
    "email": "baz@gmail.com"
}

### Get all users
GET http://localhost:3001/user/


### Get user by ID
GET http://localhost:3001/user/me